//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class departamento
    {
        public departamento()
        {
            this.promocion = new HashSet<promocion>();
        }
    
        public int id_departamento { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<promocion> promocion { get; set; }
    }
}
