//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil_cliente
    {
        public perfil_cliente()
        {
            this.cliente = new HashSet<cliente>();
            this.promocion = new HashSet<promocion>();
        }
    
        public int id_perfil_cliente { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<cliente> cliente { get; set; }
        public virtual ICollection<promocion> promocion { get; set; }
    }
}
