//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESB.BalizaWs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="BalizaWs.BalizaWS")]
    public interface BalizaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BalizaWS/getVisitasRequest", ReplyAction="http://ws/BalizaWS/getVisitasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESB.BalizaWs.getVisitasResponse getVisitas(ESB.BalizaWs.getVisitasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BalizaWS/getVisitasRequest", ReplyAction="http://ws/BalizaWS/getVisitasResponse")]
        System.Threading.Tasks.Task<ESB.BalizaWs.getVisitasResponse> getVisitasAsync(ESB.BalizaWs.getVisitasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jaxb.dev.java.net/array")]
    public partial class stringArray : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVisitas", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getVisitasRequest {
        
        public getVisitasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVisitasResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getVisitasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESB.BalizaWs.stringArray[] @return;
        
        public getVisitasResponse() {
        }
        
        public getVisitasResponse(ESB.BalizaWs.stringArray[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BalizaWSChannel : ESB.BalizaWs.BalizaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BalizaWSClient : System.ServiceModel.ClientBase<ESB.BalizaWs.BalizaWS>, ESB.BalizaWs.BalizaWS {
        
        public BalizaWSClient() {
        }
        
        public BalizaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BalizaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BalizaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BalizaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESB.BalizaWs.getVisitasResponse ESB.BalizaWs.BalizaWS.getVisitas(ESB.BalizaWs.getVisitasRequest request) {
            return base.Channel.getVisitas(request);
        }
        
        public ESB.BalizaWs.stringArray[] getVisitas() {
            ESB.BalizaWs.getVisitasRequest inValue = new ESB.BalizaWs.getVisitasRequest();
            ESB.BalizaWs.getVisitasResponse retVal = ((ESB.BalizaWs.BalizaWS)(this)).getVisitas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESB.BalizaWs.getVisitasResponse> ESB.BalizaWs.BalizaWS.getVisitasAsync(ESB.BalizaWs.getVisitasRequest request) {
            return base.Channel.getVisitasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESB.BalizaWs.getVisitasResponse> getVisitasAsync() {
            ESB.BalizaWs.getVisitasRequest inValue = new ESB.BalizaWs.getVisitasRequest();
            return ((ESB.BalizaWs.BalizaWS)(this)).getVisitasAsync(inValue);
        }
    }
}
