//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_CRM.ESB_WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<System.Nullable<int>> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ESB_WS.ESBWSSoap")]
    public interface ESBWSSoap {
        
        // CODEGEN: Generating message contract since element name getVisitasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVisitas", ReplyAction="*")]
        UI_CRM.ESB_WS.getVisitasResponse getVisitas(UI_CRM.ESB_WS.getVisitasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVisitas", ReplyAction="*")]
        System.Threading.Tasks.Task<UI_CRM.ESB_WS.getVisitasResponse> getVisitasAsync(UI_CRM.ESB_WS.getVisitasRequest request);
        
        // CODEGEN: Generating message contract since element name getVisitasPorIdClienteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVisitasPorIdCliente", ReplyAction="*")]
        UI_CRM.ESB_WS.getVisitasPorIdClienteResponse getVisitasPorIdCliente(UI_CRM.ESB_WS.getVisitasPorIdClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVisitasPorIdCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<UI_CRM.ESB_WS.getVisitasPorIdClienteResponse> getVisitasPorIdClienteAsync(UI_CRM.ESB_WS.getVisitasPorIdClienteRequest request);
        
        // CODEGEN: Generating message contract since element name nombreZona from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarZona", ReplyAction="*")]
        UI_CRM.ESB_WS.insertarZonaResponse insertarZona(UI_CRM.ESB_WS.insertarZonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarZona", ReplyAction="*")]
        System.Threading.Tasks.Task<UI_CRM.ESB_WS.insertarZonaResponse> insertarZonaAsync(UI_CRM.ESB_WS.insertarZonaRequest request);
        
        // CODEGEN: Generating message contract since element name mensaje from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarMensajeCliente", ReplyAction="*")]
        UI_CRM.ESB_WS.enviarMensajeClienteResponse enviarMensajeCliente(UI_CRM.ESB_WS.enviarMensajeClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarMensajeCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<UI_CRM.ESB_WS.enviarMensajeClienteResponse> enviarMensajeClienteAsync(UI_CRM.ESB_WS.enviarMensajeClienteRequest request);
        
        // CODEGEN: Generating message contract since element name idClientes from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarMensajeClientes", ReplyAction="*")]
        UI_CRM.ESB_WS.enviarMensajeClientesResponse enviarMensajeClientes(UI_CRM.ESB_WS.enviarMensajeClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarMensajeClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<UI_CRM.ESB_WS.enviarMensajeClientesResponse> enviarMensajeClientesAsync(UI_CRM.ESB_WS.enviarMensajeClientesRequest request);
        
        // CODEGEN: Generating message contract since element name mensaje from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarMensajeZona", ReplyAction="*")]
        UI_CRM.ESB_WS.enviarMensajeZonaResponse enviarMensajeZona(UI_CRM.ESB_WS.enviarMensajeZonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarMensajeZona", ReplyAction="*")]
        System.Threading.Tasks.Task<UI_CRM.ESB_WS.enviarMensajeZonaResponse> enviarMensajeZonaAsync(UI_CRM.ESB_WS.enviarMensajeZonaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVisitasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVisitas", Namespace="http://tempuri.org/", Order=0)]
        public UI_CRM.ESB_WS.getVisitasRequestBody Body;
        
        public getVisitasRequest() {
        }
        
        public getVisitasRequest(UI_CRM.ESB_WS.getVisitasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getVisitasRequestBody {
        
        public getVisitasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVisitasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVisitasResponse", Namespace="http://tempuri.org/", Order=0)]
        public UI_CRM.ESB_WS.getVisitasResponseBody Body;
        
        public getVisitasResponse() {
        }
        
        public getVisitasResponse(UI_CRM.ESB_WS.getVisitasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getVisitasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UI_CRM.ESB_WS.ArrayOfString getVisitasResult;
        
        public getVisitasResponseBody() {
        }
        
        public getVisitasResponseBody(UI_CRM.ESB_WS.ArrayOfString getVisitasResult) {
            this.getVisitasResult = getVisitasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVisitasPorIdClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVisitasPorIdCliente", Namespace="http://tempuri.org/", Order=0)]
        public UI_CRM.ESB_WS.getVisitasPorIdClienteRequestBody Body;
        
        public getVisitasPorIdClienteRequest() {
        }
        
        public getVisitasPorIdClienteRequest(UI_CRM.ESB_WS.getVisitasPorIdClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getVisitasPorIdClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCliente;
        
        public getVisitasPorIdClienteRequestBody() {
        }
        
        public getVisitasPorIdClienteRequestBody(int idCliente) {
            this.idCliente = idCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVisitasPorIdClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVisitasPorIdClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public UI_CRM.ESB_WS.getVisitasPorIdClienteResponseBody Body;
        
        public getVisitasPorIdClienteResponse() {
        }
        
        public getVisitasPorIdClienteResponse(UI_CRM.ESB_WS.getVisitasPorIdClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getVisitasPorIdClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UI_CRM.ESB_WS.ArrayOfString getVisitasPorIdClienteResult;
        
        public getVisitasPorIdClienteResponseBody() {
        }
        
        public getVisitasPorIdClienteResponseBody(UI_CRM.ESB_WS.ArrayOfString getVisitasPorIdClienteResult) {
            this.getVisitasPorIdClienteResult = getVisitasPorIdClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarZonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarZona", Namespace="http://tempuri.org/", Order=0)]
        public UI_CRM.ESB_WS.insertarZonaRequestBody Body;
        
        public insertarZonaRequest() {
        }
        
        public insertarZonaRequest(UI_CRM.ESB_WS.insertarZonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarZonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreZona;
        
        public insertarZonaRequestBody() {
        }
        
        public insertarZonaRequestBody(string nombreZona) {
            this.nombreZona = nombreZona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarZonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarZonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public UI_CRM.ESB_WS.insertarZonaResponseBody Body;
        
        public insertarZonaResponse() {
        }
        
        public insertarZonaResponse(UI_CRM.ESB_WS.insertarZonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarZonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertarZonaResult;
        
        public insertarZonaResponseBody() {
        }
        
        public insertarZonaResponseBody(bool insertarZonaResult) {
            this.insertarZonaResult = insertarZonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarMensajeClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviarMensajeCliente", Namespace="http://tempuri.org/", Order=0)]
        public UI_CRM.ESB_WS.enviarMensajeClienteRequestBody Body;
        
        public enviarMensajeClienteRequest() {
        }
        
        public enviarMensajeClienteRequest(UI_CRM.ESB_WS.enviarMensajeClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enviarMensajeClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        public enviarMensajeClienteRequestBody() {
        }
        
        public enviarMensajeClienteRequestBody(int idCliente, string mensaje) {
            this.idCliente = idCliente;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarMensajeClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviarMensajeClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public UI_CRM.ESB_WS.enviarMensajeClienteResponseBody Body;
        
        public enviarMensajeClienteResponse() {
        }
        
        public enviarMensajeClienteResponse(UI_CRM.ESB_WS.enviarMensajeClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enviarMensajeClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool enviarMensajeClienteResult;
        
        public enviarMensajeClienteResponseBody() {
        }
        
        public enviarMensajeClienteResponseBody(bool enviarMensajeClienteResult) {
            this.enviarMensajeClienteResult = enviarMensajeClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarMensajeClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviarMensajeClientes", Namespace="http://tempuri.org/", Order=0)]
        public UI_CRM.ESB_WS.enviarMensajeClientesRequestBody Body;
        
        public enviarMensajeClientesRequest() {
        }
        
        public enviarMensajeClientesRequest(UI_CRM.ESB_WS.enviarMensajeClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enviarMensajeClientesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UI_CRM.ESB_WS.ArrayOfInt idClientes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        public enviarMensajeClientesRequestBody() {
        }
        
        public enviarMensajeClientesRequestBody(UI_CRM.ESB_WS.ArrayOfInt idClientes, string mensaje) {
            this.idClientes = idClientes;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarMensajeClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviarMensajeClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public UI_CRM.ESB_WS.enviarMensajeClientesResponseBody Body;
        
        public enviarMensajeClientesResponse() {
        }
        
        public enviarMensajeClientesResponse(UI_CRM.ESB_WS.enviarMensajeClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enviarMensajeClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool enviarMensajeClientesResult;
        
        public enviarMensajeClientesResponseBody() {
        }
        
        public enviarMensajeClientesResponseBody(bool enviarMensajeClientesResult) {
            this.enviarMensajeClientesResult = enviarMensajeClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarMensajeZonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviarMensajeZona", Namespace="http://tempuri.org/", Order=0)]
        public UI_CRM.ESB_WS.enviarMensajeZonaRequestBody Body;
        
        public enviarMensajeZonaRequest() {
        }
        
        public enviarMensajeZonaRequest(UI_CRM.ESB_WS.enviarMensajeZonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enviarMensajeZonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idZona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        public enviarMensajeZonaRequestBody() {
        }
        
        public enviarMensajeZonaRequestBody(int idZona, string mensaje) {
            this.idZona = idZona;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarMensajeZonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviarMensajeZonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public UI_CRM.ESB_WS.enviarMensajeZonaResponseBody Body;
        
        public enviarMensajeZonaResponse() {
        }
        
        public enviarMensajeZonaResponse(UI_CRM.ESB_WS.enviarMensajeZonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enviarMensajeZonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool enviarMensajeZonaResult;
        
        public enviarMensajeZonaResponseBody() {
        }
        
        public enviarMensajeZonaResponseBody(bool enviarMensajeZonaResult) {
            this.enviarMensajeZonaResult = enviarMensajeZonaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ESBWSSoapChannel : UI_CRM.ESB_WS.ESBWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ESBWSSoapClient : System.ServiceModel.ClientBase<UI_CRM.ESB_WS.ESBWSSoap>, UI_CRM.ESB_WS.ESBWSSoap {
        
        public ESBWSSoapClient() {
        }
        
        public ESBWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ESBWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESBWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESBWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UI_CRM.ESB_WS.getVisitasResponse UI_CRM.ESB_WS.ESBWSSoap.getVisitas(UI_CRM.ESB_WS.getVisitasRequest request) {
            return base.Channel.getVisitas(request);
        }
        
        public UI_CRM.ESB_WS.ArrayOfString getVisitas() {
            UI_CRM.ESB_WS.getVisitasRequest inValue = new UI_CRM.ESB_WS.getVisitasRequest();
            inValue.Body = new UI_CRM.ESB_WS.getVisitasRequestBody();
            UI_CRM.ESB_WS.getVisitasResponse retVal = ((UI_CRM.ESB_WS.ESBWSSoap)(this)).getVisitas(inValue);
            return retVal.Body.getVisitasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UI_CRM.ESB_WS.getVisitasResponse> UI_CRM.ESB_WS.ESBWSSoap.getVisitasAsync(UI_CRM.ESB_WS.getVisitasRequest request) {
            return base.Channel.getVisitasAsync(request);
        }
        
        public System.Threading.Tasks.Task<UI_CRM.ESB_WS.getVisitasResponse> getVisitasAsync() {
            UI_CRM.ESB_WS.getVisitasRequest inValue = new UI_CRM.ESB_WS.getVisitasRequest();
            inValue.Body = new UI_CRM.ESB_WS.getVisitasRequestBody();
            return ((UI_CRM.ESB_WS.ESBWSSoap)(this)).getVisitasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UI_CRM.ESB_WS.getVisitasPorIdClienteResponse UI_CRM.ESB_WS.ESBWSSoap.getVisitasPorIdCliente(UI_CRM.ESB_WS.getVisitasPorIdClienteRequest request) {
            return base.Channel.getVisitasPorIdCliente(request);
        }
        
        public UI_CRM.ESB_WS.ArrayOfString getVisitasPorIdCliente(int idCliente) {
            UI_CRM.ESB_WS.getVisitasPorIdClienteRequest inValue = new UI_CRM.ESB_WS.getVisitasPorIdClienteRequest();
            inValue.Body = new UI_CRM.ESB_WS.getVisitasPorIdClienteRequestBody();
            inValue.Body.idCliente = idCliente;
            UI_CRM.ESB_WS.getVisitasPorIdClienteResponse retVal = ((UI_CRM.ESB_WS.ESBWSSoap)(this)).getVisitasPorIdCliente(inValue);
            return retVal.Body.getVisitasPorIdClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UI_CRM.ESB_WS.getVisitasPorIdClienteResponse> UI_CRM.ESB_WS.ESBWSSoap.getVisitasPorIdClienteAsync(UI_CRM.ESB_WS.getVisitasPorIdClienteRequest request) {
            return base.Channel.getVisitasPorIdClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<UI_CRM.ESB_WS.getVisitasPorIdClienteResponse> getVisitasPorIdClienteAsync(int idCliente) {
            UI_CRM.ESB_WS.getVisitasPorIdClienteRequest inValue = new UI_CRM.ESB_WS.getVisitasPorIdClienteRequest();
            inValue.Body = new UI_CRM.ESB_WS.getVisitasPorIdClienteRequestBody();
            inValue.Body.idCliente = idCliente;
            return ((UI_CRM.ESB_WS.ESBWSSoap)(this)).getVisitasPorIdClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UI_CRM.ESB_WS.insertarZonaResponse UI_CRM.ESB_WS.ESBWSSoap.insertarZona(UI_CRM.ESB_WS.insertarZonaRequest request) {
            return base.Channel.insertarZona(request);
        }
        
        public bool insertarZona(string nombreZona) {
            UI_CRM.ESB_WS.insertarZonaRequest inValue = new UI_CRM.ESB_WS.insertarZonaRequest();
            inValue.Body = new UI_CRM.ESB_WS.insertarZonaRequestBody();
            inValue.Body.nombreZona = nombreZona;
            UI_CRM.ESB_WS.insertarZonaResponse retVal = ((UI_CRM.ESB_WS.ESBWSSoap)(this)).insertarZona(inValue);
            return retVal.Body.insertarZonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UI_CRM.ESB_WS.insertarZonaResponse> UI_CRM.ESB_WS.ESBWSSoap.insertarZonaAsync(UI_CRM.ESB_WS.insertarZonaRequest request) {
            return base.Channel.insertarZonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UI_CRM.ESB_WS.insertarZonaResponse> insertarZonaAsync(string nombreZona) {
            UI_CRM.ESB_WS.insertarZonaRequest inValue = new UI_CRM.ESB_WS.insertarZonaRequest();
            inValue.Body = new UI_CRM.ESB_WS.insertarZonaRequestBody();
            inValue.Body.nombreZona = nombreZona;
            return ((UI_CRM.ESB_WS.ESBWSSoap)(this)).insertarZonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UI_CRM.ESB_WS.enviarMensajeClienteResponse UI_CRM.ESB_WS.ESBWSSoap.enviarMensajeCliente(UI_CRM.ESB_WS.enviarMensajeClienteRequest request) {
            return base.Channel.enviarMensajeCliente(request);
        }
        
        public bool enviarMensajeCliente(int idCliente, string mensaje) {
            UI_CRM.ESB_WS.enviarMensajeClienteRequest inValue = new UI_CRM.ESB_WS.enviarMensajeClienteRequest();
            inValue.Body = new UI_CRM.ESB_WS.enviarMensajeClienteRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.mensaje = mensaje;
            UI_CRM.ESB_WS.enviarMensajeClienteResponse retVal = ((UI_CRM.ESB_WS.ESBWSSoap)(this)).enviarMensajeCliente(inValue);
            return retVal.Body.enviarMensajeClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UI_CRM.ESB_WS.enviarMensajeClienteResponse> UI_CRM.ESB_WS.ESBWSSoap.enviarMensajeClienteAsync(UI_CRM.ESB_WS.enviarMensajeClienteRequest request) {
            return base.Channel.enviarMensajeClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<UI_CRM.ESB_WS.enviarMensajeClienteResponse> enviarMensajeClienteAsync(int idCliente, string mensaje) {
            UI_CRM.ESB_WS.enviarMensajeClienteRequest inValue = new UI_CRM.ESB_WS.enviarMensajeClienteRequest();
            inValue.Body = new UI_CRM.ESB_WS.enviarMensajeClienteRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.mensaje = mensaje;
            return ((UI_CRM.ESB_WS.ESBWSSoap)(this)).enviarMensajeClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UI_CRM.ESB_WS.enviarMensajeClientesResponse UI_CRM.ESB_WS.ESBWSSoap.enviarMensajeClientes(UI_CRM.ESB_WS.enviarMensajeClientesRequest request) {
            return base.Channel.enviarMensajeClientes(request);
        }
        
        public bool enviarMensajeClientes(UI_CRM.ESB_WS.ArrayOfInt idClientes, string mensaje) {
            UI_CRM.ESB_WS.enviarMensajeClientesRequest inValue = new UI_CRM.ESB_WS.enviarMensajeClientesRequest();
            inValue.Body = new UI_CRM.ESB_WS.enviarMensajeClientesRequestBody();
            inValue.Body.idClientes = idClientes;
            inValue.Body.mensaje = mensaje;
            UI_CRM.ESB_WS.enviarMensajeClientesResponse retVal = ((UI_CRM.ESB_WS.ESBWSSoap)(this)).enviarMensajeClientes(inValue);
            return retVal.Body.enviarMensajeClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UI_CRM.ESB_WS.enviarMensajeClientesResponse> UI_CRM.ESB_WS.ESBWSSoap.enviarMensajeClientesAsync(UI_CRM.ESB_WS.enviarMensajeClientesRequest request) {
            return base.Channel.enviarMensajeClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UI_CRM.ESB_WS.enviarMensajeClientesResponse> enviarMensajeClientesAsync(UI_CRM.ESB_WS.ArrayOfInt idClientes, string mensaje) {
            UI_CRM.ESB_WS.enviarMensajeClientesRequest inValue = new UI_CRM.ESB_WS.enviarMensajeClientesRequest();
            inValue.Body = new UI_CRM.ESB_WS.enviarMensajeClientesRequestBody();
            inValue.Body.idClientes = idClientes;
            inValue.Body.mensaje = mensaje;
            return ((UI_CRM.ESB_WS.ESBWSSoap)(this)).enviarMensajeClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UI_CRM.ESB_WS.enviarMensajeZonaResponse UI_CRM.ESB_WS.ESBWSSoap.enviarMensajeZona(UI_CRM.ESB_WS.enviarMensajeZonaRequest request) {
            return base.Channel.enviarMensajeZona(request);
        }
        
        public bool enviarMensajeZona(int idZona, string mensaje) {
            UI_CRM.ESB_WS.enviarMensajeZonaRequest inValue = new UI_CRM.ESB_WS.enviarMensajeZonaRequest();
            inValue.Body = new UI_CRM.ESB_WS.enviarMensajeZonaRequestBody();
            inValue.Body.idZona = idZona;
            inValue.Body.mensaje = mensaje;
            UI_CRM.ESB_WS.enviarMensajeZonaResponse retVal = ((UI_CRM.ESB_WS.ESBWSSoap)(this)).enviarMensajeZona(inValue);
            return retVal.Body.enviarMensajeZonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UI_CRM.ESB_WS.enviarMensajeZonaResponse> UI_CRM.ESB_WS.ESBWSSoap.enviarMensajeZonaAsync(UI_CRM.ESB_WS.enviarMensajeZonaRequest request) {
            return base.Channel.enviarMensajeZonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UI_CRM.ESB_WS.enviarMensajeZonaResponse> enviarMensajeZonaAsync(int idZona, string mensaje) {
            UI_CRM.ESB_WS.enviarMensajeZonaRequest inValue = new UI_CRM.ESB_WS.enviarMensajeZonaRequest();
            inValue.Body = new UI_CRM.ESB_WS.enviarMensajeZonaRequestBody();
            inValue.Body.idZona = idZona;
            inValue.Body.mensaje = mensaje;
            return ((UI_CRM.ESB_WS.ESBWSSoap)(this)).enviarMensajeZonaAsync(inValue);
        }
    }
}
